#! /usr/bin/env bash
# sync public folder to server

# rsync -av -e "ssh -i $KOTSF_KEY" /usr/local/src/kotsf-blog/public/ ubuntu@kotsf.com:/usr/local/src/kotsf-blog/public
aws --profile taw s3 sync public/ s3://tilting-at-windmills
